kind: "BuildConfig"
apiVersion: "v1"
metadata:
    name: "mediawiki-build"
spec:
    runPolicy: "Serial"
    triggers:
        - type: "ImageChange"
    source:
        git:
            uri: "https://github.com/wikimedia/mediawiki"
            ref: "1.34.0"
    strategy:
        sourceStrategy:
            from:
              kind: "DockerImage"
              name: "centos/php-73-centos7:latest"
    output: 
        to:
            kind: "ImageStreamTag"
            name: "mediawiki:1.34.0"