apiVersion: v1
kind: Service
metadata:
  name: dbpedia-mediawiki
spec:
  selector:
    app: dbpedia-mediawiki
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: mediawiki