kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "dbpedia-mediawiki"
spec:
  template: 
    metadata:
      labels:
        name: "dbpedia-mediawiki"
    spec:
      containers:
        - name: "dbpedia-mediawiki"
          image: "docker-registry.default.svc:5000/eudbpedia/mediawiki:1.34.0"
          ports:
            - containerPort: 8080
              protocol: "TCP"
          volumeMounts:
            - mountPath: /opt/app-root/src/images
              name: dbpedia-pvc
              subPath: mediawiki-images
            - mountPath: /opt/app-root/src/LocalSettings.php
              name: dbpedia-secrets
              subPath: LocalSettings.php
      volumes:
        - name: dbpedia-pvc
          persistentVolumeClaim:
            claimName: dbpedia-pvc
        - name: dbpedia-secrets
          secret:
            secretName: dbpedia-secrets
            items:
              - key: LocalSettings.php
                path: LocalSettings.php
  replicas: 1
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "dbpedia-mediawiki"
        from:
          kind: "ImageStreamTag"
          name: "mediawiki:1.34.0"
  strategy: 
    type: "Rolling"
  paused: false 
  revisionHistoryLimit: 2 
  minReadySeconds: 0