apiVersion: batch/v1
kind: Job
metadata:
  name: acme-issue
spec:
  parallelism: 1
  completions: 1
  template:         
    metadata:
      name: acme-issue
    spec:
        containers:
        - name: acme-issue
          image: docker-registry.default.svc:5000/eudbpedia/openshift-acme
          args: ["--issue",  "-d", "eudbpedia.apps.openshift.deustotech.eu", "--webroot", "/nginx-root", "--config-home", "/config", "--key-file", "/certs/server.key", "--fullchain-file", "/certs/server.crt"]
          volumeMounts:
            - mountPath: /nginx-root
              name: dbpedia-pvc
              subPath: nginx-root
            - mountPath: /certs
              name: dbpedia-pvc
              subPath: certs
        volumes:
        - name: dbpedia-pvc
          persistentVolumeClaim:
            claimName: dbpedia-pvc
        restartPolicy: OnFailure