kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "dbpedia-nginx"
spec:
  template: 
    metadata:
      labels:
        name: "dbpedia-nginx"
    spec:
      containers:
        - name: "dbpedia-nginx"
          image: "docker-registry.default.svc:5000/eudbpedia/dbpedia-nginx"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "dbpedia-nginx"
        from:
          kind: "ImageStreamTag"
          name: "dbpedia-nginx:latest"
  strategy: 
    type: "Rolling"
  paused: false 
  revisionHistoryLimit: 2 
  minReadySeconds: 0