apiVersion: v1
kind: Route
metadata:
  name: eudbpedia.apps.openshift.deustotech.eu
  annotations:
    kubernetes.io/tls-acme: 'true'
spec:
  host: eudbpedia.apps.openshift.deustotech.eu
  path: /
  to:
    kind: Service
    name: dbpedia-mediawiki
  port:
    targetPort: 80

---

apiVersion: v1
kind: Route
metadata:
    name: eudbpedia.apps.openshift.deustotech.eu-conductor
    annotations:
        kubernetes.io/tls-acme: 'true'    
spec:
    host: eudbpedia.apps.openshift.deustotech.eu
    path: /conductor
    to:
        kind: Service
        name: dbpedia
    port:
        targetPort: 8890