apiVersion: v1
kind: DeploymentConfig
metadata:
  name: dbpedia
spec:
  template:
    metadata:
      labels: 
        name: dbpedia
    spec:
      containers:
        - name: dbpedia
          image: docker-registry-default.apps.openshift.deustotech.eu/eudbpedia/virtuoso
          env:
            - name: NumberOfBuffers
              valueFrom:
                configMapKeyRef:
                    key: NumberOfBuffers
                    name: dbpedia-config
          volumeMounts:
            - mountPath: /var/lib/virtuoso-opensource-7
              name: dbpedia-pvc
              subPath: db
            - mountPath: /var/lib/virtuoso-opensource-7/set_registry_values.sql
              name: dbpedia-config
              subPath: set_registry_values.sql
            - mountPath: /import
              name: dbpedia-pvc
              subPath: triples
      volumes:
        - name: dbpedia-pvc
          persistentVolumeClaim:
            claimName: dbpedia-pvc
        - name: dbpedia-config
          configMap:
            name: dbpedia-config
            items:
              - key: set_registry_values.sql
                path: set_registry_values.sql
    replicas: 1
    triggers:
      - type: "ConfigChange" 
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
            - "dbpedia"
          from:
            kind: "ImageStreamTag"
            name: "virtuoso"
    strategy: 
      type: "Rolling"
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds: 0