apiVersion: v1
kind: Route
metadata:
  name: eudbpedia.apps.openshift.deustotech.eu
  # annotations:
    # kubernetes.io/tls-acme: 'true'
spec:
  host: eudbpedia.apps.openshift.deustotech.eu
  path: /
  to:
    kind: Service
    name: dbpedia-nginx
  port:
    targetPort: 80